apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu 
    spec:
      containers:
      - name: ubuntu-container
        image: docker.io/shridhanr/ubuntu:latest
        ports:
        - containerPort: 22
      imagePullSecrets:
      - name: regcred
        
---

apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
spec:
  selector:
    app: ubuntu 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 31022
