apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
  labels:
    app: apache2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2 
    spec:
      containers:
      - name: apache2-container
        image: docker.io/shridhanr/apache2:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
        
---

apiVersion: v1
kind: Service
metadata:
  name: apache2-service
spec:
  selector:
    app: apache2 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31080
