apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: haystack
  name: haystack-ext
  namespace: customer-1
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: haystack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: haystack
    spec:
      containers:
      - image: shridhanr/bonsai-main:latest
        imagePullPolicy: Always
        name: bonsai-main-container
        volumes:
        - name: appdata-vol
          configMap:
            name: app/data
        - name: appmodels-vol
          configMap:
            name: app/models  
      - image: shridhanr/bonsai-action:latest
        imagePullPolicy: Always
        name: bonsai-action-container
      imagePullSecrets:
      - name: image-pull-secret
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: main-server
  namespace: customer-1
spec:
  type: ClusterIP
  selector:
    app: haystack
  ports:
    - port: 5005
      targetPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: action-server
  namespace: customer-1
spec:
  type: ClusterIP
  selector:
    app: haystack
  ports:
    - port: 5055
      targetPort: 5055