---
#Rasa Actions and Backend Deoplyment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rasaactionsnbackend
  name: rasaactionsnbackend
  namespace: customer-1
spec:
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - non-gpu
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rasaactionsnbackend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rasaactionsnbackend
    spec:
      containers:
      - image: shridhanr/bonsai-rasaactions:latest
        imagePullPolicy: Always
        name: bonsai-rasaactions-container
        volumes:
        - name: appdata-vol
          configMap:
            name: app/data
        - name: appmodels-vol
          configMap:
            name: app/models  
      - image: shridhanr/bonsai-rasabackend:latest
        imagePullPolicy: Always
        name: bonsai-rasabackend-container
      imagePullSecrets:
      - name: image-pull-secret
      restartPolicy: Always
---
#Rasa Actions Service
apiVersion: v1
kind: Service
metadata:
  name: np-rasaactionsnbackend
  namespace: customer-1
spec:
  type: NodePort
  ports:
  - port: 5055
    targetPort: 5055
    name: rasaactionsnbackend
    nodePort: 31055
  selector:
    app: rasaactionsnbackend


---
#Rasa Actions Service
apiVersion: v1
kind: Service
metadata:
  name: np-rasaactions
  namespace: customer-1
spec:
  type: NodePort
  ports:
  - port: 5005
    targetPort: 5005
    name: rasaactions
    nodePort: 31005
  selector:
    app: rasaactionsnbackend

