
FROM rasa/rasa:2.5.0

WORKDIR /app
COPY . /app

COPY backend/data /app/data
RUN chdir /backend/app/data
RUN chmod +x /.config

RUN  rasa train

VOLUME /app
VOLUME /app/data
VOLUME /app/models

CMD [ "run","-m","/app/models","--enable-api","--cors","*","--debug", "--endpoints", "endpoints.yml" ]