
FROM rasa/rasa:2.5.0

WORKDIR /app
COPY . /app
COPY backend/data /app/data

RUN pwd

RUN  rasa train --config=backend/config.yml

VOLUME /app
VOLUME /app/data
VOLUME /app/models

CMD [ "run","-m","/app/models","--enable-api","--cors","*","--debug", "--endpoints", "backend/endpoints.yml" ]